In [2]:
import numpy as np

file = r"../section1_images/40156103_34_3.csv"
file2 = "../section1_images/40156103_22_5.csv"
lessequals = np.loadtxt(file, delimiter = ',', dtype = int)
b = np.loadtxt(file2, delimiter = ',', dtype = int)
file3 = "../section1_images/40156103_24_2.csv"
d = np.loadtxt(file3, delimiter = ',', dtype = int)

print(b)
print()
print(d)
print()
print(lessequals)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

[[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0

The output above shows that I have successfully loaded my csv files and they've been converted to numpy arrays so that their features can be calculated.

Below I'll start on the two functions of label and index - which are used to uniquely identify the images. This is done by passing the filename to the function and splitting the filename string where necessary 

In [3]:
#Returns label of the image file, representing the true symbol of the image. All files are of the same length so all label codes are
#in the same index in each string
def label(filename):
    return filename[-8:-6]

#Code for this function is likewise to above
def index(filename):
    return filename[-5:-4]




# Counting Black Pixels

<b>The next several methods are largely similar in that in a variety of ways they count the amount of black pixels in the image</b>

In [4]:
#Function returns number of black pixels in an image
def nr_pix(array):
    black_pixels = 0
    for row in array:
        for item in row:
            if item == 1:
                black_pixels += 1
    return black_pixels


#Function counts the amount of rows with at least one black pixel in row
def height(array):
    black_pixels = 0
    for row in array:
        if 1 in row:
            black_pixels +=1             
    return black_pixels


#This was my first way of dealing with columns as opposed to rows but I later discovered the transpose method which allowed me to
#flip rows and columns. It takes up less memory as an array doesn't need to be created each time and it allows reuse of code between 
#the row methods and column methods
"""#Function counts the amount of rows with at least one black pixel in column
def width(array):
    black_pixels = 0
    columns = [] # This array will be used later to keep track of all columns that have at least one black pixel in them
    for row in array:
        for index, item in enumerate(row):
            if index in columns: # If statement checks if index is in columns that have already logged that they have a black pixel
                continue  #continue to next iteration in for loop if a black pixel has already been logged in column index
            if item == 1:
                black_pixels +=1
                columns.append(index)  
    return black_pixels
    """

# Basically the same function as the height method but has the array transposed so we can treat columns  
# as if they're rows and so we can use the for loop on them easily and effectively
def width(array):
    black_pixels = 0
    for column in array.T:
        if 1 in column:
            black_pixels +=1             
    return black_pixels


def tallness(array):
    return height(array)/width(array)


def rows_with_1(array):
    black_pixels = 0
    for row in array:
        black_pixels_in_row = 0 # Checks how many black_pixels are in the row. Resets to 0 after every new instance of row
        for item in row:
            if item == 1:
                black_pixels_in_row += 1
        if black_pixels_in_row == 1:
            black_pixels += 1
    return black_pixels  


#Same as above function but array is transposed
def cols_with_1(array):
    black_pixels = 0
    for column in array.T: #transpose array to make columns rows so we can use a for loop on them
        black_pixels_in_col = 0
        for item in column:
            if item == 1:
                black_pixels_in_col += 1
        if black_pixels_in_col == 1:
            black_pixels += 1
    return black_pixels


#Reused code here but instead of checking for only one black pixel in row we check if black_pixels_in_row 
#is greater than or equal to 5
def rows_with_5_plus(array):
    black_pixels = 0
    for row in array:
        black_pixels_in_row = 0
        for item in row:
            if item == 1:
                black_pixels_in_row += 1
        if black_pixels_in_row >= 5:
            black_pixels += 1
    return black_pixels


#Same as above function but array is transposed
def cols_with_5_plus(array):
    black_pixels = 0
    for column in array.T:
        black_pixels_in_col = 0
        for item in column:
            if item == 1:
                black_pixels_in_col += 1
        if black_pixels_in_col >= 5:
            black_pixels += 1
    return black_pixels




# Neighbours features

<b> Below is the code that dealt largely with neghbour pixels in my dataset. Again the functions are largely simliar within this section, however they are more complicated to calculate.

In [5]:
#The function below returns all of the neighbours of an element of index rowi, coli in arr array and returns it as a numpy array
def get_neighbours(rowi, coli, array):
    neighbours = []
    for i in range(-1, 2):
        for j in range(-1, 2):
            if i == 0 and j == 0: # Make sure to skip over the actual item itself
                continue
            try:
                neighbours.append(array[rowi + i][coli + j]) 
# We iterate through all elements in array arr surrounding arr[rowi][coli] here, the for loop starts at arr[rowi - 1][coli - 1]
# (upper-left) and continues on to arr[rowi - 1][coli + 0] and so on... 
# We add these elements to the empty list of neighbours which we created at the start of the function                
            except IndexError: 
                pass        
# We make sure to catch instances of index errors because at the edges of our image matrix IndexError exceptions will be thrown
    return np.array(neighbours)


def one_neighbour(array):
    exact_one_neighbour = 0 
    for rowi, row in enumerate(array):  # row in this context is an array, not an index, rowi allows us to access the index of the row
        for coli, item in enumerate(row): # likewise for columns
            if item == 0: # if pixel is not black, continue to next iteration of the for loop
                continue
            #otherwise get all the neighbours for the black pixel    
            neighbours = get_neighbours(rowi, coli, array)
            
# neighbours = np.array([array[rowi - 1][index - 1], array[rowi][index - 1],array[row + 1][index - 1],\
# array[row - 1][index], array[row + 1][index], array[row - 1][index + 1],  \
# array[row][index + 1], array[row + 1][index + 1]])

# I was considering the code above to log the neighbouring pixels but the try except block didn't work for it as it  
# skipped the entire iteration of the for loop if just one exception within all of the neighbours was raised, 
# rather than just passing on if there was an individual error with one of the neighbours like I wanted

            if np.sum(neighbours) == 1:
# If there's only one black pixel in the entire nparray of neighbours then the total sum should be equal to 1
                exact_one_neighbour += 1 # If true; we increment the exact_one_neighbour counter
    return exact_one_neighbour
            
    
#This function is nearly absolutely identical to the one_neighbour function, except it checks if the sum of neighbours is >= 3
# rather than equal to 1 which is what it was before. This is noted by the comment in the method below
def three_or_more_neighbours(array):
    three_or_more_neighbours = 0 
    for rowi, row in enumerate(array):  
        for coli, item in enumerate(row):
            if item == 0: 
                continue   
            neighbours = get_neighbours(rowi, coli, array) 
            if np.sum(neighbours) >= 3: 
# If there's more than 3 black pixels in the nparray of neighbours then the total sum should be greater than or equal to 3
                three_or_more_neighbours += 1 
    return three_or_more_neighbours

# I was going to make a new function for each different type of method for counting neighbours but I decided against it
#as it made the overall code unneccessarily long with too many methods and it takes up more memory than necessary
"""
def get_neighbours_below(rowi, coli, arr):
    neighbours = []
    for i in range(1, 2): #rows are i
        for j in range(-1, 2): # columns are j
            try:
                neighbours.append(arr[rowi + i][coli + j]) # We iterate through all elements in array arr surrounding arr[rowi][coli] here, the for loop starts at arr[rowi - 1][coli - 1]
                                                           # (upper-left) and continues on to arr[rowi - 1][coli + 0] and so on... 
                                                           #We add them to the empty list of neighbours which we created at the start of the function
            except IndexError: 
                pass        # We make sure to catch instances of index errors because at the edges of our image matrix these exceptions will be thrown
            
    return np.array(neighbours)
"""

def no_neighbours_below(array):
    no_neighbours_below = 0 
    for rowi, row in enumerate(array):  
        for coli, item in enumerate(row):
            if item == 0: 
                continue
#This below block of code is basically a copy of the get_neghbours function however we only count rows in range 1, 2 (which means we
#only count the rows + 1 in our for loop). The rows + 1 in relation to our pixel are the rows below it in the nparray matrix
            neighbours = []
            for i in range(1, 2): #rows are i
                for j in range(-1, 2): # columns are j
                    try:
                        neighbours.append(array[rowi + i][coli + j])
                    except IndexError: 
                        pass 
            neighbours = np.array(neighbours) 
            
            if np.sum(neighbours) == 0: 
                no_neighbours_below += 1 
    return no_neighbours_below


def no_neighbours_above(array):
    no_neighbours_above = 0 
    for rowi, row in enumerate(array):  
        for coli, item in enumerate(row): 
            if item == 0: 
                continue         
# This next block of code is a reused version of the get_neighbours function but instead only the rows equal to -1 are 
# iterated in the i loop because we only want the neighbours above the pixel we are evaluating
            neighbours = []
            for i in range(-1, 0): #rows are i
                for j in range(-1, 2): # columns are j
                    try:
                        neighbours.append(array[rowi + i][coli + j]) 
                    except IndexError: 
                        pass       
                    
            neighbours = np.array(neighbours) 
            if np.sum(neighbours) == 0: 
                no_neighbours_above += 1  
    return no_neighbours_above


def no_neighbours_before(array):
    no_neighbours_before = 0 
    for rowi, row in enumerate(array):  
        for coli, item in enumerate(row): 
            if item == 0: 
                continue            
# This next block of code is a reused version of the get_neighbours function but instead only in
# the columns equal to -1 are iterated the i loop because we only want the neighbours before the pixel we are evaluating
            neighbours = []
            for i in range(-1, 2): 
                for j in range(-1, 0): 
                    try:
                        neighbours.append(array[rowi + i][coli + j]) 
                    except IndexError: 
                        pass    
                    
            neighbours = np.array(neighbours)
            if np.sum(neighbours) == 0: 
                no_neighbours_before += 1         
    return no_neighbours_before


def no_neighbours_after(array):
    no_neighbours_after = 0 
    for rowi, row in enumerate(array):  
        for coli, item in enumerate(row): 
            if item == 0:
                continue          
# This next block of code is a reused version of the get_neighbours function but instead only 
# the columns equal to +1 are iterated in the j loop because we only want the neighbours after the pixel we are evaluating
            neighbours = []
            for i in range(-1, 2): #rows are i
                for j in range(1, 2): # columns are j
                    try:
                        neighbours.append(array[rowi + i][coli + j]) 
                    except IndexError: 
                        pass         
                    
            neighbours = np.array(neighbours) 
            if np.sum(neighbours) == 0: 
                no_neighbours_after += 1 
                
    return no_neighbours_after



In [6]:
file4 = r"../section1_images/40156103_37_5.csv"
file5 = r"../section1_images/40156103_34_5.csv"
approx = np.loadtxt(file4, delimiter = ',', dtype = int)
lessequal = np.loadtxt(file5, delimiter = ',', dtype = int)
print(approx)
print()
print(lessequal)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0

# Searching neighbours
<b> What the next few methods have in common is that they all use a recursive search to search through neighbouring pixels and keep recursively searching until they have found all neighbouring black pixels. nr_regions calculates the amount of separate connected maximal black pixel sections there are in an image and nr_eyes calculaates how many regions of whitespace are surrounded by black pixels, i.e 'e' and 'a' have eyes but a letter like 'f' does not.  

In [7]:
def searchNeighbours(array, i, j, visited):
        
        visited[i][j] = True
        for x in range(-1, 2):
            for y in range(-1, 2):
                if x == 0 and y == 0: # Make sure to skip over the actual item itself
                    continue
                if -1 < i + x < 20 and -1 < j + y < 20: #keep within index range of the pixel array
                    if not visited[i + x][j + y] and array[i + x][j + y] == 1:
            #Recursively searches each connected black pixel until they've all been visited          
                        searchNeighbours(array, i + x, j + y, visited)
                        #print(array[i + x][j + y])
                    
#visited is included in params so it's visited status can be kept track of over recursions

#visited =  [[False for j in range(20)]for i in range(20)] 
#searchNeighbours(approx, 6, 10, visited)

In [8]:
def nr_regions(array):
    visited =  [[False for i in range(20)]for j in range(20)] 
#Above I create a 2D boolean array equal in size to the pixel array I'm measuring
    count = 0
    for rowi, row in enumerate(array):  
        for coli, item in enumerate(row):
            if array[rowi][coli] == 1 and visited[rowi][coli] == False:
                searchNeighbours(array, rowi, coli, visited)
                count +=1 
#Every time a new region is found the searchNeighbours function wll trigger, 
#this count keeps track of it
    return count
  
           
print("Number or regions of b: ", nr_regions(b))   
print("Number or regions of a less than or equals sign: ", nr_regions(lessequals))                       

Number or regions of b:  1
Number or regions of a less than or equals sign:  2


<b>I first thought that the nr_regions function would work if I just substituted the seaching through the ones in the numpy array for zeroes then subtracting the result by one. However this was not the case, the function alwyas returned one - I discovered after looking at the numpy arrays for a while that the 0's in the eye of the shape were connected diagonally to those 0's outside the shape. So I created this variation of my searchNeighbours function below: </b>

In [9]:
def searchNeighboursNoDiagonal(array, i, j, visited):
        
        visited[i][j] = True
        for x in range(-1, 2):
            for y in range(-1, 2):
                if abs(x) == abs(y):
                    continue
#if x and y are (-1, -1), (-1, 1), (1, -1), (1, 1) then they're diagonally connected and we skip these neighbours
#if x and y are 0 and 0 then it's the item itself and we skip that too
                if -1 < i + x < 20 and -1 < j + y < 20: #keep within index range of the pixel array
                    if not visited[i + x][j + y] and array[i + x][j + y] == 0:
            #Recursively searches each connected black pixel until they've all been visited          
                        searchNeighboursNoDiagonal(array, i + x, j + y, visited)
                        #print(array[i + x][j + y])
def nr_eyes(array):
    visited =  [[False for i in range(20)]for j in range(20)] 
#Above I create a 2D boolean array equal in size to the pixel array I'm measuring
    count = 0
    for rowi, row in enumerate(array):  
        for coli, item in enumerate(row):
            if array[rowi][coli] == 0 and visited[rowi][coli] == False:
                searchNeighboursNoDiagonal(array, rowi, coli, visited)
                count +=1 
#Every time a new region is found the searchNeighbours function wll trigger, this count keeps track of it
    return count - 1

#return count - 1 because the function without it would return the whitespace outside
#of the symbol, plus the eye surrounded by the black pixels in the symbol
print("Number of eyes in less than or equals sign: " ,nr_eyes(lessequals))
print(lessequals)
print("\nNumber of eyes in b: " ,nr_eyes(b))
print(b)
print("\nNumber of eyes in d: " ,nr_eyes(d))
print(d)


Number of eyes in less than or equals sign:  0
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

Number of eyes in b:  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 

# Other Features and exporting the results to a csv file

<b>Also, as we can see above, the d is different from the b in that it's long line is on the right of the pixel array rather than the left. I can distinguish between the two symbols by making sure that the long line starts on the right side by having a variation of the cols with 5+ feature be on only array[col] beyond the midway point (give a couple of pixel positions maybe for margin of error). With my variation I'll want my cols with 5+ feature to be an even greater line of columns with black pixels in a row so an error has less likelihood of happening</b>

In [10]:
def r5_c5(array):
    return rows_with_5_plus(array) - cols_with_5_plus(array)
    

def b_or_d(array):
    targetcol = 0
    for coli, column in enumerate(array.T):
        black_pixels_in_col = 0
        for item in column:
            if item == 1:
                black_pixels_in_col += 1
        if black_pixels_in_col >= 7:
            targetcol = coli
#Above code targets a column with 7 or more black pixels in a row 
#this column index is the column where the long line of the d or the b is
    if targetcol < 10:
        return "b" 
    else:
        return "d"
            
            
print("Shape is a d")
print("Testing whether symbol is a b or a d:" , b_or_d(d))
print("\nShape is a b")
print("Testing whether symbol is a b or a d:" , b_or_d(b))
print()

Shape is a d
Testing whether symbol is a b or a d: d

Shape is a b
Testing whether symbol is a b or a d: b



In [11]:
def identify_isolated_horizontal(array):
    horizontal_line = 0
    for rowi, row in enumerate(array):
        if (horizontal_line == 1):
            continue
        targetrow = 0
        black_pixels_in_row = 0
        for item in row:
            if item == 1:
                black_pixels_in_row += 1
        if black_pixels_in_row >= 5:
            targetrow = rowi
            isolate = 0
            for i in range (1, 20):
                if (array[targetrow][i] == 1):
                    if(array[targetrow + 1][i] == 0 and array[targetrow - 1][i] == 0):
                        isolate += 1
                else:
                    break
            if isolate >=5:
                horizontal_line = 1
    return horizontal_line

def identify_isolated_vertical(array):
    vertical_line = 0
    for coli, col in enumerate(array.T):
        if (vertical_line == 1):
            continue
        targetcol = 0
        black_pixels_in_col = 0
        for item in col:
            if item == 1:
                black_pixels_in_col += 1
        if black_pixels_in_col >= 5:
            targetcol = coli
            isolate = 0
            for i in range (1, 20):
                if (array.T[targetcol][i] == 1):
                    if(array.T[targetcol + 1][i] == 0 and array.T[targetcol - 1][i] == 0):
                        isolate += 1
                else:
                    break
            if isolate >=5:
                vertical_line = 1               
    return vertical_line


print("\nTesting if identify horizontal function works for less_equals- should return 1:\n",\
      identify_isolated_horizontal(lessequals))
print("\nTesting if identify horizontal function works for b - should return 0:\n", \
      identify_isolated_horizontal(d))
print("\nTesting if identify vertical function works for less_equals- should return 0:\n",\
      identify_isolated_vertical(lessequals))
print("\nTesting if identify vertical function works for d - should return 1:\n", \
      identify_isolated_vertical(d))


Testing if identify horizontal function works for less_equals- should return 1:
 1

Testing if identify horizontal function works for b - should return 0:
 0

Testing if identify vertical function works for less_equals- should return 0:
 0

Testing if identify vertical function works for d - should return 1:
 1


In [12]:
import pandas as pd
import os

def calculate_features(directory):
    npfeatures_file = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
    for root, dirs, files in os.walk(directory):
        for file in files:
            filename = directory + "\\" + file
            b = np.loadtxt(filename, delimiter = ',', dtype = int)
            
            featurenp = np.array([label(filename), index(filename), nr_pix(b), height(b), width(b), tallness(b),\
         rows_with_1(b),cols_with_1(b), rows_with_5_plus(b), cols_with_5_plus(b), \
        one_neighbour(b), three_or_more_neighbours(b), no_neighbours_below(b), \
        no_neighbours_above(b), no_neighbours_before(b), no_neighbours_after(b), \
        nr_regions(b), nr_eyes(b), r5_c5(b)])
            
            npfeatures_file = np.vstack((npfeatures_file, featurenp))
    npfeatures_file = np.delete(npfeatures_file, 0, 0) 
#Deletes the top row of the npfeatures_file array which was made at the start ([0,0,0....])
    return npfeatures_file

            
print(calculate_features(r"../section1_images"))
df = pd.DataFrame(calculate_features(r"../section1_images"))
df.to_csv("../section2_features/40156103_features.csv", index = False, header = False )

#https://stackoverflow.com/questions/9775297/append-a-numpy-array-to-a-numpy-array#comment12441795_9775378


[['11' '1' '26' ... '1' '0' '0']
 ['11' '2' '28' ... '1' '0' '0']
 ['11' '3' '36' ... '1' '0' '-1']
 ...
 ['37' '6' '45' ... '2' '0' '3']
 ['37' '7' '40' ... '2' '0' '1']
 ['37' '8' '42' ... '2' '0' '4']]
